- name: Install python3
  hosts: yum_example
  remote_user: deployer

  tasks:
  - name: Ensure python3 is at the latest version
    ansible.builtin.yum:
      name: python3
      state: present
    become: true
