- name: create a new user
  hosts: ubuntu
  remote_user: deployer
  vars:
    username: test123
    password: abc123!

  tasks: 
    - name: Check User Status
      user:
        name: "{{ username }}"
        password: "{{password | password_hash('sha512', 'saltySaltine') }}" 
        shell: /bin/bash
        createhome: yes
        state: present
      become: true
