- name: Install docker
  hosts: apt_example
  remote_user: deployer
  become: true
  become_user: root

    tasks:
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
    become: yes
  
