- name: Creates a new domain user with the name Test123
  hosts: windows
  become_method: runas
  tasks:
  - name: create a new domain user
	microsoft.ad.user:
  	identity: Test123
  	firstname: Test
  	surname: User
  	password: abc123!
  	state: present
  	groups:
    	set:
    	- Domain Admins
    	- Domain Users
  	domain_username: bickenbugget-adm
  	domain_password: abc123!
  	domain_server: bickenbugget.local
