- name: Install mediawiki on docker
  hosts: apt_example
  remote_user: deployer
  become: true
  become_user: root

    tasks:
    - name: Ensure docker is at the latest version
      ansible.builtin.apt:
        name: docker
        state: latest
  
    - name: Start docker service
      ansible.builtin.shell: systemctl start docker
  
    - name: Enable docker service
      ansible.builtin.shell: systemctl enable docker
  
   - name: Get the media wiki image
      docker_image:
        name: mediawiki
        source: pull
  
    - name: Create a docker container
      docker_container:
        name: mediawiki_container
        image: mediawiki
        ports: 
          - "8080:80"
        state: started
