- name: Install python3
  hosts: yum-example
  remote_user: deployer

  tasks:
  - name: Ensure python3 is at the latest version
    ansible.builtin.yum:
      name: python3
      state: latest
    become: true
    become_user: root
    become_password: abc123!
